# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escriba su nombre', max_length=50)),
                ('telephone', models.CharField(help_text='Ingrese su numero de teléfono', max_length=10)),
                ('sexo', models.CharField(help_text='Ingrese cual es su sexo (F)(M)', max_length=1)),
                ('fechanacimiento', models.DateField()),
            ],
        ),
    ]
